#!/usr/bin/env node
/**
 * GitHub Project Sync
 *
 * Syncs project configuration from project.yml to GitHub Projects v2.
 * Also auto-links all organization repositories to the project.
 *
 * Uses the gh CLI for GraphQL API calls.
 *
 * Required environment variable: GH_TOKEN
 * In CI, this is a GitHub App installation token generated by actions/create-github-app-token
 * using PROJECT_APP_ID and PROJECT_APP_PRIVATE_KEY secrets.
 *
 * @see https://docs.github.com/en/issues/planning-and-tracking-with-projects
 */

import { readFileSync } from 'fs';
import { execSync } from 'child_process';
import { parse } from 'yaml';

// =============================================================================
// Configuration
// =============================================================================

const CONFIG_PATH = 'project.yml';
const config = parse(readFileSync(CONFIG_PATH, 'utf8'));

// =============================================================================
// Logging Utilities
// =============================================================================

const log = {
  header: (msg) => console.log(`\n=== ${msg} ===\n`),
  info: (msg) => console.log(msg),
  success: (msg) => console.log(`  \u2713 ${msg}`),
  warn: (msg) => console.warn(`  \u26a0 ${msg}`),
  error: (msg) => console.error(`  \u2717 ${msg}`),
  field: (name, status) => console.log(`  [${name}] ${status}`),
};

// =============================================================================
// GraphQL Client
// =============================================================================

/**
 * Escape a string for use in GraphQL inline values
 */
function escapeGraphQL(str) {
  return (str || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Execute a GraphQL query using the gh CLI
 */
function graphql(query, variables = {}) {
  const variableArgs = Object.entries(variables)
    .map(([key, value]) => {
      const flag = typeof value === 'string' ? '-f' : '-F';
      return `${flag} ${key}=${JSON.stringify(value)}`;
    })
    .join(' ');

  const escapedQuery = query.replace(/'/g, "'\\''");
  const cmd = `gh api graphql -f query='${escapedQuery}' ${variableArgs}`.trim();

  try {
    const result = execSync(cmd, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] });
    const parsed = JSON.parse(result);

    if (parsed.errors) {
      const errorMsg = parsed.errors.map((e) => e.message).join('; ');
      throw new Error(errorMsg);
    }

    return parsed.data;
  } catch (error) {
    if (error.stdout) {
      try {
        const response = JSON.parse(error.stdout);
        if (response.errors) {
          throw new Error(response.errors.map((e) => e.message).join('; '));
        }
      } catch {
        // Ignore parse errors, use original error
      }
    }
    throw error;
  }
}

/**
 * Execute a GraphQL mutation with inline values (for complex nested objects)
 */
function graphqlInline(query) {
  const escapedQuery = query.replace(/'/g, "'\\''");
  const cmd = `gh api graphql -f query='${escapedQuery}'`;

  const result = execSync(cmd, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] });
  const parsed = JSON.parse(result);

  if (parsed.errors) {
    const errorMsg = parsed.errors.map((e) => e.message).join('; ');
    throw new Error(errorMsg);
  }

  return parsed.data;
}

// =============================================================================
// Error Handling
// =============================================================================

function isAlreadyExistsError(error) {
  const msg = error.message || '';
  return (
    msg.includes('already been taken') || msg.includes('reserved') || msg.includes('already linked')
  );
}

function handleExistsError(fn, resourceName) {
  return async (...args) => {
    try {
      return await fn(...args);
    } catch (error) {
      if (isAlreadyExistsError(error)) {
        log.warn(`${resourceName} already exists or is reserved, skipping`);
        return null;
      }
      throw error;
    }
  };
}

// =============================================================================
// Project Operations
// =============================================================================

async function findProject(owner, title) {
  const data = graphql(
    `
      query ($owner: String!, $first: Int!) {
        organization(login: $owner) {
          projectsV2(first: $first) {
            nodes {
              id
              title
              number
            }
          }
        }
      }
    `,
    { owner, first: 20 },
  );

  const project = data.organization?.projectsV2?.nodes?.find((p) => p.title === title);
  return project ? { id: project.id, number: project.number } : null;
}

async function createProject(projectConfig) {
  const orgData = graphql(
    `
      query ($owner: String!) {
        organization(login: $owner) {
          id
        }
      }
    `,
    { owner: projectConfig.owner },
  );

  const createData = graphql(
    `
      mutation ($ownerId: ID!, $title: String!) {
        createProjectV2(input: { ownerId: $ownerId, title: $title }) {
          projectV2 {
            id
            number
          }
        }
      }
    `,
    { ownerId: orgData.organization.id, title: projectConfig.title },
  );

  const p = createData.createProjectV2.projectV2;
  return { id: p.id, number: p.number };
}

async function getProjectFields(projectId) {
  const data = graphql(
    `
      query ($projectId: ID!) {
        node(id: $projectId) {
          ... on ProjectV2 {
            fields(first: 50) {
              nodes {
                ... on ProjectV2Field {
                  id
                  name
                  dataType
                }
                ... on ProjectV2SingleSelectField {
                  id
                  name
                  dataType
                  options {
                    id
                    name
                    color
                    description
                  }
                }
                ... on ProjectV2IterationField {
                  id
                  name
                  dataType
                }
              }
            }
          }
        }
      }
    `,
    { projectId },
  );

  return data.node.fields.nodes;
}

// =============================================================================
// Field Operations
// =============================================================================

const FIELD_TYPES = {
  single_select: 'SINGLE_SELECT',
  date: 'DATE',
  text: 'TEXT',
};

function buildOption(option) {
  const name = escapeGraphQL(option.name);
  const color = option.color || 'GRAY';
  const description = escapeGraphQL(option.description || '');
  return `{ name: "${name}", color: ${color}, description: "${description}" }`;
}

async function createSimpleField(projectId, fieldConfig, dataType) {
  const data = graphql(
    `
      mutation ($projectId: ID!, $name: String!) {
        createProjectV2Field(
          input: { projectId: $projectId, dataType: ${dataType}, name: $name }
        ) {
          projectV2Field {
            ... on ProjectV2Field {
              id
            }
          }
        }
      }
    `,
    { projectId, name: fieldConfig.name },
  );

  return data.createProjectV2Field.projectV2Field.id;
}

async function createSingleSelectField(projectId, fieldConfig) {
  const options = (fieldConfig.options || []).map(buildOption);

  if (options.length === 0) {
    throw new Error(`Single select field "${fieldConfig.name}" requires at least one option`);
  }

  const query = `
    mutation {
      createProjectV2Field(input: {
        projectId: "${projectId}",
        dataType: SINGLE_SELECT,
        name: "${escapeGraphQL(fieldConfig.name)}",
        singleSelectOptions: [${options.join(', ')}]
      }) {
        projectV2Field {
          ... on ProjectV2SingleSelectField {
            id
          }
        }
      }
    }
  `;

  const data = graphqlInline(query);
  return data.createProjectV2Field.projectV2Field.id;
}

async function updateSingleSelectOptions(fieldId, desiredOptions, existingOptions) {
  const existingNames = new Set((existingOptions || []).map((o) => o.name));
  const missingOptions = desiredOptions.filter((o) => !existingNames.has(o.name));

  if (missingOptions.length === 0) {
    log.success('Options up to date');
    return;
  }

  log.info(
    `    Adding ${missingOptions.length} option(s): ${missingOptions.map((o) => o.name).join(', ')}`,
  );

  const allOptions = [...(existingOptions || []), ...missingOptions].map(buildOption);

  const query = `
    mutation {
      updateProjectV2Field(input: {
        fieldId: "${fieldId}",
        singleSelectOptions: [${allOptions.join(', ')}]
      }) {
        projectV2Field {
          ... on ProjectV2SingleSelectField {
            id
          }
        }
      }
    }
  `;

  try {
    graphqlInline(query);
    log.success('Options updated');
  } catch (error) {
    log.warn(`Could not update options: ${error.message}`);
  }
}

async function createField(projectId, fieldConfig) {
  const safeCreate = handleExistsError(async () => {
    switch (fieldConfig.type) {
      case 'single_select':
        return await createSingleSelectField(projectId, fieldConfig);
      case 'date':
      case 'text':
        return await createSimpleField(projectId, fieldConfig, FIELD_TYPES[fieldConfig.type]);
      default:
        log.warn(`Unknown field type: ${fieldConfig.type}`);
        return null;
    }
  }, `Field "${fieldConfig.name}"`);

  return safeCreate();
}

async function syncField(projectId, fieldConfig, existingFields) {
  const existing = existingFields.find((f) => f.name === fieldConfig.name);

  if (existing) {
    log.field(fieldConfig.name, 'exists');

    if (fieldConfig.type === 'single_select' && fieldConfig.options) {
      await updateSingleSelectOptions(existing.id, fieldConfig.options, existing.options);
    }
  } else {
    log.field(fieldConfig.name, 'creating...');
    await createField(projectId, fieldConfig);
  }
}

// =============================================================================
// Repository Operations
// =============================================================================

/**
 * List all repositories in the organization
 */
async function listOrgRepos(owner) {
  const result = execSync(`gh repo list ${owner} --limit 100 --json name --no-archived`, {
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  return JSON.parse(result).map((r) => r.name);
}

/**
 * Get all repositories linked to a project
 */
async function getLinkedRepositories(projectId) {
  const data = graphql(
    `
      query ($projectId: ID!) {
        node(id: $projectId) {
          ... on ProjectV2 {
            repositories(first: 100) {
              nodes {
                nameWithOwner
              }
            }
          }
        }
      }
    `,
    { projectId },
  );

  return data.node.repositories.nodes.map((r) => r.nameWithOwner);
}

/**
 * Link all organization repositories to the project.
 * Skips repos that are already linked.
 */
async function linkAllOrgRepos(projectNumber, owner) {
  const orgRepos = await listOrgRepos(owner);
  const linkedRepos = await getLinkedRepositories(
    (await findProject(owner, config.project.title)).id,
  );
  const linkedSet = new Set(linkedRepos.map((r) => r.toLowerCase()));

  let linked = 0;
  for (const repo of orgRepos) {
    const fullName = `${owner}/${repo}`.toLowerCase();
    if (linkedSet.has(fullName)) {
      log.success(`${repo} already linked`);
      continue;
    }

    try {
      execSync(`gh project link ${projectNumber} --owner ${owner} --repo ${owner}/${repo}`, {
        encoding: 'utf8',
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      log.success(`${repo} linked`);
      linked++;
    } catch (error) {
      log.warn(`Could not link ${repo}: ${error.message}`);
    }
  }

  if (linked > 0) {
    log.info(`  Linked ${linked} new repo(s)`);
  }
}

/**
 * Verify that specific repositories are linked (optional check)
 */
async function verifyRepositories(projectId, owner, requiredRepos) {
  const linkedRepos = await getLinkedRepositories(projectId);
  const linkedSet = new Set(linkedRepos.map((r) => r.toLowerCase()));

  const missing = [];
  for (const repo of requiredRepos) {
    const fullName = `${owner}/${repo}`.toLowerCase();
    if (linkedSet.has(fullName)) {
      log.success(`${owner}/${repo} is linked`);
    } else {
      log.error(`${owner}/${repo} is NOT linked`);
      missing.push(`${owner}/${repo}`);
    }
  }

  return missing;
}

// =============================================================================
// Main
// =============================================================================

async function main() {
  const { project, fields } = config;

  log.header('GitHub Project Sync');
  log.info(`Project: ${project.title}`);
  log.info(`Owner:   ${project.owner}`);

  // 1. Find or create project
  log.header('Project');
  let projectInfo = await findProject(project.owner, project.title);

  if (!projectInfo) {
    log.info('Creating project...');
    projectInfo = await createProject(project);
    log.success(`Created: ${projectInfo.id} (number: ${projectInfo.number})`);
  } else {
    log.success(`Found: ${projectInfo.id} (number: ${projectInfo.number})`);
  }

  // 2. Sync fields
  log.header('Fields');
  const existingFields = await getProjectFields(projectInfo.id);

  for (const field of fields) {
    await syncField(projectInfo.id, field, existingFields);
  }

  // 3. Auto-link all org repos
  log.header('Repositories (auto-link)');
  await linkAllOrgRepos(projectInfo.number, project.owner);

  // 4. Verify required repos are linked
  if (project.verify_repositories?.length > 0) {
    log.header('Repositories (verify)');
    const missing = await verifyRepositories(
      projectInfo.id,
      project.owner,
      project.verify_repositories,
    );

    if (missing.length > 0) {
      log.warn(`${missing.length} required repo(s) not linked — check warnings above`);
    }
  }

  log.header('Sync Complete');
}

main().catch((error) => {
  log.error(error.message);
  process.exit(1);
});
